name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.10.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image using Docker Compose
        run: |
          docker-compose build

      - name: Capture the image ID
        run: |
          IMAGE_ID=$(docker images --format '{{.Repository}}:{{.Tag}}' | grep 'app' | head -n 1)
          echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV

      - name: Tag and push the image using the captured ID
        run: |
          export IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)
          docker tag $IMAGE_ID 866934333672.dkr.ecr.ap-northeast-1.amazonaws.com/teamprojectrepo:$IMAGE_TAG
          docker push 866934333672.dkr.ecr.ap-northeast-1.amazonaws.com/teamprojectrepo:$IMAGE_TAG

      - name: Update Kubernetes deployment file with the new image
        run: |
          export IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)
          echo "IMAGE_TAG is: $IMAGE_TAG"
          sed -i "s|image: 866934333672.dkr.ecr.ap-northeast-1.amazonaws.com/teamprojectrepo:.*|image: 866934333672.dkr.ecr.ap-northeast-1.amazonaws.com/teamprojectrepo:$IMAGE_TAG|g" dep_app.yaml
          cat dep_app.yaml  # Optional: For debugging, to check the file after update.

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Set up EKS cluster context
        run: |
          aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name team-3

      - name: Apply Kubernetes configurations
        run: |
          kubectl apply -f dep_db_pv.yaml
          kubectl apply -f dep_db.yaml
          kubectl apply -f dep_app.yaml
          kubectl apply -f dep_test.yaml

      - name: Verify deployment
        run: |
          kubectl rollout status deployment/flask-app